import React from 'react';
import { motion } from 'framer-motion';
import { Code2, Brain } from 'lucide-react';

const techStack = [
  { category: 'Frontend', items: ['React 18', 'TypeScript', 'Vite', 'Tailwind CSS', 'Recharts', 'Plotly.js', 'Framer Motion'] },
  { category: 'Backend', items: ['Flask', 'Python 3.12', 'SQLAlchemy', 'yfinance', 'Pandas', 'NumPy'] },
  { category: 'Machine Learning', items: ['TensorFlow/Keras (LSTM)', 'Scikit-learn', 'XGBoost', 'MinMaxScaler'] },
  { category: 'Database', items: ['SQLite', 'PostgreSQL-ready'] },
];

const About: React.FC = () => {
  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-3xl font-bold gradient-text inline-block">StockVision AI</h1>
        <p className="text-lg text-muted-foreground mt-2 leading-relaxed">
          An intelligent stock forecasting and financial analytics platform that combines
          real-time market data with machine learning to predict stock prices and provide
          comprehensive financial insights.
        </p>
      </motion.div>

      {/* Features */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="glass-card p-6">
        <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
          <Brain className="w-5 h-5 text-primary" /> Key Features
        </h2>
        <ul className="space-y-2 text-sm text-muted-foreground">
          <li>• Real-time stock data from Yahoo Finance (US, Indian, and global exchanges)</li>
          <li>• 15+ technical indicators (SMA, EMA, RSI, MACD, Bollinger Bands, ATR, etc.)</li>
          <li>• Financial analytics (Sharpe, Sortino, CAGR, Max Drawdown, Volatility)</li>
          <li>• 4 ML models: LSTM, Random Forest, XGBoost, Linear Regression</li>
          <li>• Automatic model comparison and best model selection</li>
          <li>• Smart model caching — models retrain only when data changes</li>
          <li>• 1-day, 7-day, and 30-day forecasts with confidence intervals</li>
          <li>• Interactive charts (candlestick, price, volume, technical overlays)</li>
          <li>• Stock comparison (up to 3 stocks)</li>
          <li>• Watchlist with persistent storage</li>
          <li>• CSV data export</li>
          <li>• Dark/Light theme</li>
        </ul>
      </motion.div>

      {/* Tech Stack */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
        <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
          <Code2 className="w-5 h-5 text-primary" /> Technology Stack
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {techStack.map(({ category, items }) => (
            <div key={category} className="glass-card p-5">
              <h3 className="text-sm font-semibold text-primary mb-3">{category}</h3>
              <div className="flex flex-wrap gap-2">
                {items.map(item => (
                  <span key={item} className="px-2.5 py-1 text-xs rounded-full bg-secondary text-foreground">
                    {item}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Disclaimer */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-6 border-l-4 border-l-amber-500">
        <h3 className="text-sm font-semibold text-amber-400 mb-2">⚠️ Disclaimer</h3>
        <p className="text-xs text-muted-foreground leading-relaxed">
          This application is for educational and informational purposes only. Stock price predictions
          are generated by machine learning models and should not be used as financial advice.
          Past performance does not guarantee future results. Always consult a qualified financial
          advisor before making investment decisions.
        </p>
      </motion.div>
    </div>
  );
};

export default About;
